modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "%%modissue%%"
license = "GPL-3.0-only"

[[mods]]
modId = "%%modid%%"
version = "${version}"
displayName = "%%modname%%"
authors = "MrMelon54"
description = "${description}"
logoFile = "icon.png"
displayURL = "%%modwebsite%%"

[[dependencies.%%modid%%]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_minecraft_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.%%modid%%]]
modId = "infrastructury"
mandatory = true
versionRange = "[${infrastructury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.%%modid%%]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
