modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "GPL-3.0-only"

[[mods]]
modId = "%%modid%%"
version = "${version}"
displayName = "%%modname%%"
authors = "MrMelon54"
description = "%%moddesc%%"
#logoFile = ""

[[dependencies.%%modid%%]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.%%modid%%]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.%%modid%%]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"
