modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "%%modissue%%"
license = "GPL-3.0-only"

[[mods]]
modId = "%%modid%%"
version = "${version}"
displayName = "%%modname%%"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.%%modid%%]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.%%modid%%]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
